# Generated by Django 2.2 on 2021-09-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
